export const USER_ACTION = {
  GET_ONLINE_FRIENDS: "USER_GET_ONLINE_FRIENDS",
  GET_ONLINE_FRIENDS_REQUESTED: "GET_ONLINE_FRIENDS_REQUESTED",
  GET_ONLINE_FRIENDS_SUCCESS: "GET_ONLINE_FRIENDS_SUCCESS",

  GET_POST_REQUESTED: "GET_POST_REQUESTED",
  GET_POST_SUCCESS: "GET_POST_SUCCESS",
  GET_POST_FAILED: "GET_POST_FAILED",

  GET_SHORTCURT_REQUESTED: "GET_SHORTCURT_REQUESTED",
  GET_SHORTCURT_SUCCESS: "GET_SHORTCURT_SUCCESS",
  GET_SHORTCURT_FAILED: "GET_SHORTCURT_FAILED",

  GET_PROFILE_REQUESTED: "GET_PROFILE_REQUESTED",
  GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
  GET_PROFILE_FAILED: "GET_PROFILE_FAILED",
};

export const AUTHEN_ACTION = {
  MAKE_LOGIN_REQUESTED: "MAKE_LOGIN_REQUESTED",
  MAKE_LOGIN_SUCCESS: "MAKE_LOGIN_SUCCESS",
  MAKE_LOGIN_FAILED: "MAKE_LOGIN_FAILED",

  MAKE_LOGOUT_REQUESTED: "MAKE_LOGOUT_REQUESTED",
  MAKE_LOGOUT_SUCCESS: "MAKE_LOGOUT_SUCCESS",

  UPDATE_CURRENT_USER: "UPDATE_CURRENT_USER",

  GET_USER_REQUESTED: "GET_USER_REQUESTED",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAILED: "GET_USER_FAILED",
};

export const POST_ACTION = {
  CREATE_POST_REQUESTED: "CREATE_POST_REQUESTED",
  CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
  CREATE_POST_FAILED: "CREATE_POST_FAILED",

  DELETE_POST_REQUESTED: "DELETE_POST_REQUESTED",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  DELETE_POST_FAILED: "DELETE_POST_FAILED",

  UPDATE_POST_REQUESTED: "UPDATE_POST_REQUESTED",
  UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
  UPDATE_POST_FAILED: "UPDATE_POST_FAILED",

  LOAD_MORE_POST_REQUESTED: "LOAD_MORE_POST_REQUESTED",
  LOAD_MORE_POST_SUCCESS: "LOAD_MORE_POST_SUCCESS",
  LOAD_MORE_POST_FAILED: "LOAD_MORE_POST_FAILED",
};
